services:
  db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=changeit
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
